/* tslint:disable */
/* eslint-disable */
/**
 * ZZOL API
 * ZZOL api 목록
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 토큰
 * @export
 * @interface AuthTokens
 */
export interface AuthTokens {
  /**
   *
   * @type {string}
   * @memberof AuthTokens
   */
  accessToken?: string;
  /**
   *
   * @type {string}
   * @memberof AuthTokens
   */
  refreshToken?: string;
  /**
   *
   * @type {string}
   * @memberof AuthTokens
   */
  grantType?: string;
  /**
   *
   * @type {number}
   * @memberof AuthTokens
   */
  expiresIn?: number;
}
/**
 * 카카오 계정 정보
 * @export
 * @interface KakaoAccountDto
 */
export interface KakaoAccountDto {
  /**
   * 카카오계정 대표 이메일
   * @type {string}
   * @memberof KakaoAccountDto
   */
  email?: string;
  /**
   * 이메일 존재 여부(deprecated)
   * @type {boolean}
   * @memberof KakaoAccountDto
   */
  has_email?: boolean;
  /**
   * 이메일 유효 여부
   * @type {boolean}
   * @memberof KakaoAccountDto
   */
  is_email_valid?: boolean;
  /**
   * 이메일 인증 여부
   * @type {boolean}
   * @memberof KakaoAccountDto
   */
  is_email_verified?: boolean;
}
/**
 * 회원 정보
 * @export
 * @interface Member
 */
export interface Member {
  /**
   * 회원번호
   * @type {number}
   * @memberof Member
   */
  memberNo: number;
  /**
   * 카카오 회원번호
   * @type {number}
   * @memberof Member
   */
  kakaoId: number;
  /**
   * 이름
   * @type {string}
   * @memberof Member
   */
  name?: string;
  /**
   * 닉네임
   * @type {string}
   * @memberof Member
   */
  nickname: string;
  /**
   * 이메일
   * @type {string}
   * @memberof Member
   */
  email: string;
  /**
   * 생년월일
   * @type {string}
   * @memberof Member
   */
  birthDate: string;
  /**
   * 프로필 이미지 url
   * @type {string}
   * @memberof Member
   */
  profileImgUrl?: string;
  /**
   * 회원가입 일시
   * @type {string}
   * @memberof Member
   */
  createDt: string;
  /**
   * 회원 상태
   * @type {string}
   * @memberof Member
   */
  memberState: string;
}
/**
 *
 * @export
 * @interface SignInResponseDto
 */
export interface SignInResponseDto {
  /**
   * 카카오 회원번호
   * @type {number}
   * @memberof SignInResponseDto
   */
  kakaoId: number;
  /**
   *
   * @type {KakaoAccountDto}
   * @memberof SignInResponseDto
   */
  kakaoAccount?: KakaoAccountDto;
  /**
   *
   * @type {Member}
   * @memberof SignInResponseDto
   */
  member?: Member;
  /**
   *
   * @type {AuthTokens}
   * @memberof SignInResponseDto
   */
  token?: AuthTokens;
  /**
   * 회원가입을 한 회원인지 여부
   * @type {boolean}
   * @memberof SignInResponseDto
   */
  isRegistered: boolean;
}
/**
 *
 * @export
 * @interface SignUpRequestDto
 */
export interface SignUpRequestDto {
  /**
   * 카카오 회원번호
   * @type {number}
   * @memberof SignUpRequestDto
   */
  kakaoId: number;
  /**
   * 닉네임
   * @type {string}
   * @memberof SignUpRequestDto
   */
  nickname: string;
  /**
   * 이메일(카카오 이메일)
   * @type {string}
   * @memberof SignUpRequestDto
   */
  email: string;
  /**
   * 생년월일
   * @type {string}
   * @memberof SignUpRequestDto
   */
  birthDate: string;
}
/**
 *
 * @export
 * @interface SignUpResponseDto
 */
export interface SignUpResponseDto {
  /**
   *
   * @type {Member}
   * @memberof SignUpResponseDto
   */
  member?: Member;
  /**
   *
   * @type {AuthTokens}
   * @memberof SignUpResponseDto
   */
  token?: AuthTokens;
}
