/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface BaseResponseKakaoSignInResponse
 */
export interface BaseResponseKakaoSignInResponse {
  /**
   *
   * @type {string}
   * @memberof BaseResponseKakaoSignInResponse
   */
  messageCode: string;
  /**
   *
   * @type {string}
   * @memberof BaseResponseKakaoSignInResponse
   */
  message: string;
  /**
   *
   * @type {KakaoSignInResponse}
   * @memberof BaseResponseKakaoSignInResponse
   */
  result?: KakaoSignInResponse | null;
}
/**
 *
 * @export
 * @interface BaseResponseKakaoSignUpResponse
 */
export interface BaseResponseKakaoSignUpResponse {
  /**
   *
   * @type {string}
   * @memberof BaseResponseKakaoSignUpResponse
   */
  messageCode: string;
  /**
   *
   * @type {string}
   * @memberof BaseResponseKakaoSignUpResponse
   */
  message: string;
  /**
   *
   * @type {KakaoSignUpResponse}
   * @memberof BaseResponseKakaoSignUpResponse
   */
  result?: KakaoSignUpResponse | null;
}
/**
 *
 * @export
 * @interface BaseResponseListMemberResponse
 */
export interface BaseResponseListMemberResponse {
  /**
   *
   * @type {string}
   * @memberof BaseResponseListMemberResponse
   */
  messageCode: string;
  /**
   *
   * @type {string}
   * @memberof BaseResponseListMemberResponse
   */
  message: string;
  /**
   *
   * @type {Array<MemberResponse>}
   * @memberof BaseResponseListMemberResponse
   */
  result?: Array<MemberResponse> | null;
}
/**
 *
 * @export
 * @interface BaseResponseMemberResponse
 */
export interface BaseResponseMemberResponse {
  /**
   *
   * @type {string}
   * @memberof BaseResponseMemberResponse
   */
  messageCode: string;
  /**
   *
   * @type {string}
   * @memberof BaseResponseMemberResponse
   */
  message: string;
  /**
   *
   * @type {MemberResponse}
   * @memberof BaseResponseMemberResponse
   */
  result?: MemberResponse | null;
}
/**
 *
 * @export
 * @interface HTTPValidationError
 */
export interface HTTPValidationError {
  /**
   *
   * @type {Array<ValidationError>}
   * @memberof HTTPValidationError
   */
  detail?: Array<ValidationError>;
}
/**
 *
 * @export
 * @interface KakaoAccount
 */
export interface KakaoAccount {
  /**
   * 카카오계정 대표 이메일
   * @type {string}
   * @memberof KakaoAccount
   */
  email: string;
  /**
   * 이메일 존재 여부(deprecated)
   * @type {boolean}
   * @memberof KakaoAccount
   */
  hasEmail: boolean;
  /**
   * 이메일 유효 여부
   * @type {boolean}
   * @memberof KakaoAccount
   */
  isEmailValid: boolean;
  /**
   * 이메일 인증 여부
   * @type {boolean}
   * @memberof KakaoAccount
   */
  isEmailVerified: boolean;
}
/**
 *
 * @export
 * @interface KakaoSignInResponse
 */
export interface KakaoSignInResponse {
  /**
   * 회원가입을 한 회원인지 여부
   * @type {boolean}
   * @memberof KakaoSignInResponse
   */
  isRegistered: boolean;
  /**
   * 카카오 회원 번호
   * @type {number}
   * @memberof KakaoSignInResponse
   */
  kakaoId: number;
  /**
   * 카카오 계정 정보
   * @type {KakaoAccount}
   * @memberof KakaoSignInResponse
   */
  kakaoAccount: KakaoAccount;
  /**
   *
   * @type {MemberResponse}
   * @memberof KakaoSignInResponse
   */
  member: MemberResponse | null;
  /**
   *
   * @type {string}
   * @memberof KakaoSignInResponse
   */
  accessToken?: string | null;
}
/**
 *
 * @export
 * @interface KakaoSignUpRequest
 */
export interface KakaoSignUpRequest {
  /**
   * 카카오 회원 번호
   * @type {number}
   * @memberof KakaoSignUpRequest
   */
  kakaoId: number;
  /**
   * 닉네임
   * @type {string}
   * @memberof KakaoSignUpRequest
   */
  nickname: string;
  /**
   * 이메일
   * @type {string}
   * @memberof KakaoSignUpRequest
   */
  email: string;
  /**
   * 생년월일
   * @type {string}
   * @memberof KakaoSignUpRequest
   */
  birthDate: string;
}
/**
 *
 * @export
 * @interface KakaoSignUpResponse
 */
export interface KakaoSignUpResponse {
  /**
   * 등록된 회원
   * @type {MemberResponse}
   * @memberof KakaoSignUpResponse
   */
  member: MemberResponse;
  /**
   *
   * @type {string}
   * @memberof KakaoSignUpResponse
   */
  accessToken?: string | null;
}
/**
 *
 * @export
 * @interface MemberResponse
 */
export interface MemberResponse {
  /**
   * 회원 번호
   * @type {number}
   * @memberof MemberResponse
   */
  memberNo: number;
  /**
   * 이메일
   * @type {string}
   * @memberof MemberResponse
   */
  email: string;
  /**
   * 카카오 회원 번호
   * @type {number}
   * @memberof MemberResponse
   */
  kakaoId: number;
  /**
   * 닉네임
   * @type {string}
   * @memberof MemberResponse
   */
  nickname: string;
  /**
   * 생년월일
   * @type {string}
   * @memberof MemberResponse
   */
  birthDate: string;
}
/**
 *
 * @export
 * @interface ValidationError
 */
export interface ValidationError {
  /**
   *
   * @type {Array<ValidationErrorLocInner>}
   * @memberof ValidationError
   */
  loc: Array<ValidationErrorLocInner>;
  /**
   *
   * @type {string}
   * @memberof ValidationError
   */
  msg: string;
  /**
   *
   * @type {string}
   * @memberof ValidationError
   */
  type: string;
}
/**
 *
 * @export
 * @interface ValidationErrorLocInner
 */
export interface ValidationErrorLocInner {}
